// Code generated by protoc-gen-go. DO NOT EDIT.
// source: placementcontroller.proto

/*
Package placementcontroller is a generated protocol buffer package.

It is generated from these files:
	placementcontroller.proto

It has these top-level messages:
	ResourceRequest
	ResourceResponse
*/
package placementcontroller

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResourceRequest struct {
	AppContext string `protobuf:"bytes,1,opt,name=appContext" json:"appContext,omitempty"`
}

func (m *ResourceRequest) Reset()                    { *m = ResourceRequest{} }
func (m *ResourceRequest) String() string            { return proto.CompactTextString(m) }
func (*ResourceRequest) ProtoMessage()               {}
func (*ResourceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ResourceRequest) GetAppContext() string {
	if m != nil {
		return m.AppContext
	}
	return ""
}

type ResourceResponse struct {
	AppContext string `protobuf:"bytes,1,opt,name=appContext" json:"appContext,omitempty"`
	Status     bool   `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Message    string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ResourceResponse) Reset()                    { *m = ResourceResponse{} }
func (m *ResourceResponse) String() string            { return proto.CompactTextString(m) }
func (*ResourceResponse) ProtoMessage()               {}
func (*ResourceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResourceResponse) GetAppContext() string {
	if m != nil {
		return m.AppContext
	}
	return ""
}

func (m *ResourceResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ResourceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ResourceRequest)(nil), "ResourceRequest")
	proto.RegisterType((*ResourceResponse)(nil), "ResourceResponse")
}

func init() { proto.RegisterFile("placementcontroller.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xc1, 0x8a, 0xc2, 0x30,
	0x14, 0x45, 0xa7, 0x33, 0xd0, 0x99, 0x79, 0x0b, 0xad, 0x11, 0x24, 0xba, 0x90, 0xd2, 0x55, 0x57,
	0x05, 0x75, 0xe1, 0x07, 0x14, 0x5c, 0x8a, 0xe4, 0x0f, 0x62, 0x7d, 0x88, 0x90, 0x26, 0x31, 0xef,
	0x05, 0xfc, 0x7c, 0xa1, 0x58, 0x95, 0x6e, 0x5c, 0xde, 0x0b, 0x07, 0xce, 0x81, 0xb9, 0x37, 0xba,
	0xc1, 0x16, 0x2d, 0x37, 0xce, 0x72, 0x70, 0xc6, 0x60, 0xa8, 0x7c, 0x70, 0xec, 0x8a, 0x15, 0x8c,
	0x15, 0x92, 0x8b, 0xa1, 0x41, 0x85, 0xd7, 0x88, 0xc4, 0x62, 0x09, 0xa0, 0xbd, 0xaf, 0x9d, 0x65,
	0xbc, 0xb1, 0x4c, 0xf2, 0xa4, 0xfc, 0x57, 0x6f, 0x4f, 0x71, 0x82, 0xec, 0x85, 0x90, 0x77, 0x96,
	0xf0, 0x13, 0x23, 0x66, 0x90, 0x12, 0x6b, 0x8e, 0x24, 0xbf, 0xf3, 0xa4, 0xfc, 0x53, 0x8f, 0x25,
	0x24, 0xfc, 0xb6, 0x48, 0xa4, 0xcf, 0x28, 0x7f, 0x3a, 0xa8, 0x9f, 0xeb, 0x3d, 0x4c, 0x0f, 0xbd,
	0x75, 0xfd, 0xb4, 0x16, 0x5b, 0x18, 0xed, 0x2e, 0x86, 0x31, 0xd4, 0x26, 0x12, 0x63, 0x20, 0x91,
	0x55, 0x83, 0x80, 0xc5, 0xa4, 0x1a, 0xfa, 0x15, 0x5f, 0xc7, 0xb4, 0xeb, 0xdd, 0xdc, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x5a, 0xaf, 0xc2, 0xec, 0x0c, 0x01, 0x00, 0x00,
}
